TCost=5+ int('5')
print(TCost)
Sno=10
print('1.My School No is {}'.format(Sno))
print('2.My School No is' +' ' + str(Sno))
print(3.4+1.4)
print("hello ", "this","is",10)

#Boolean (True or False)
print("Boopalan".isalpha())
print("Boopalan123".isalnum())
print("Boopalan The Mass".istitle())
print("Boopalan".isdigit())
print("Boopalan".islower())
print("Boopalan".isupper())
print("Boopalan".startswith('B'))
